### ISSUE TITLE
sqlmap not running & heartbeedDriver not generating pdf 

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#11]
1) In sqlmap driver ,Drivers/sqlMapDriver .no such a python file present , so prompting error in Client/node_modules/sqlMapDriver/ sqlMapDriver.py not present ???

2) Executing heartbleedDriver unable to generate pdf in UI/node/test.pdf .

3)  When i execute one tool after another , the latest tool output stored in test.pdf , need to be generate seperate pdf in UI/node/ directory as toolname_Date_time _scanID.pdf !!

**Comment by gauravpawaskar** [comment]
You need to download SQLMap tool from internet. Rename folder name to sqlmap. Place the whole sqlmap folder in sqlMapDriver folder. Now create a zip and now upload zip to server and push to client.

For nmap related tools. Please install nmap on the machine where client is. Also make sure nmap command runs. Some nmap features need root access, so please start client with Sudo.

**Comment by praveensutar** [comment]
I tried your defined procedure of sqlmap, but prompt on web  some error occurred ans crashes the attack launcher., If you provide that sqlmap zip already , it could be easy to execute. Which having that python file.

Heartbleed running properly but , generating report fail in pdf format. It is in JSON format on web

**Comment by gauravpawaskar** [comment]
Added heartbleed parser file.
