### ISSUE TITLE
nmapCipher scan not produce result

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#12]
nmapCipher scan couldnot generating report inUI/node test.pdf (empty pdf). 
Need to check once again .

**Comment by gauravpawaskar** [comment]
For nmap related tools. Please install nmap on the machine where client is. Also make sure nmap command runs. Some nmap features need root access, so please start client with Sudo.

Also let me know what is the target on which you are running the scan. Make sure that target has SSL connections. No SSL then no reports

**Comment by praveensutar** [comment]
Close this issue
