### ISSUE TITLE
Old client id tool link crashes UI 

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#15]
When i relauch framework again and again , it display old client id and their respective tools previously uploaded , after clicking specific tool ,UI crashesh.

**Comment by gauravpawaskar** [comment]
We need a db clean up. It will always show older data. We need to discuss how to tackle this issue.

**Comment by gauravpawaskar** [comment]
Resolved from startup.sh script? Please verify.

**Comment by praveensutar** [comment]
yes.. close the issue.
