### ISSUE TITLE
anyfile.tar.gz upload consumes space in UI/node/temptools & server/tools .

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#4]
uploading anyfile.tar.gz in browser responses fail status , but actually uploaded in temptools as well as server/tools directory , I think it couldn't be present in both directory otherwise it consumes lot of space. 
 It can be deleted if incorrect file uploaded.

**Comment by gauravpawaskar** [comment]
There are 2 places this file will be. UI/node folder and Sever folder. We are assuming UI and server can be hosted on different machines, so that is by design.

**Comment by praveensutar** [comment]
okay. great . what if unknown user uploads lot of filename.tar.gz , then it consume lot of space in UI/node and server folder. If filename.tar.gz invalid file format then it can be deleted on both folder , because there is no use of this file format , unwanted file get uploaded .

**Comment by gauravpawaskar** [comment]
Fixed.
