### ISSUE TITLE
server crashes when initial home page display 303 ,0 , 0 client list click

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#5]
server get crash in the path /home/ click on '0' client list

**Comment by gauravpawaskar** [comment]
Can you explain it more?

**Comment by praveensutar** [comment]
when i launched UI , there are initial three client list as 303 , 0 and 0 , ..  when i clicked on "0" ,then server get crash

**Comment by gauravpawaskar** [comment]
Hi Praveen,

Ideally there should not be client number as 0.

I would like to know how did you add client id as 0?

On Mon, Oct 12, 2015 at 9:48 PM, praveensutar notifications@github.com
wrote:

> when i launched UI , there are initial three client list as 303 , 0 and 0
> , .. when i clicked on "0" ,then server get crash
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rohitpitkeappsec/SecAutomationFramework/issues/5#issuecomment-147600324
> .

## 

Thanks and Regards,
Gaurav Pawaskar

**Comment by praveensutar** [comment]
Latest code solved this issue . Please close this issue
