### ISSUE TITLE
In the path UI browser , setting -> User client map -> User ID field having lot of admin list

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#6]
The User ID should have only one admin username or some unique user , but it contains lot of admin user by default.

**Comment by gauravpawaskar** [comment]
This is because, you must have created admin users before I fix the code. Remove all extra admins from the database manually and see if you can add more.

**Comment by praveensutar** [comment]
Ya.. it works..
