### ISSUE TITLE
Same client Id with multiple times

### ISSUE THREAD

**Issue by praveensutar** [rohitpitkeappsec/SecAutomationFramework#9]
Path - UI(Browser) - setting-> user client map -> map user and client . If I map same client ID multiple times then it create same client id multiple times in client list(/home)

May be its impact on Tools->Push to client ->pust tools (client list ) contains same Client id multiple times.

**Comment by gauravpawaskar** [comment]
fix checked in. Please verify.

**Comment by praveensutar** [comment]
ya , its working properly

**Comment by praveensutar** [comment]
Ya , its working properly . You can close this bug .
